MongoDB:
  Uri: "mongodb+srv://admin:47fMSxobbPOTepmP@cluster0-nmhgi.mongodb.net/test?retryWrites=true&w=majority"
  HostName: "localhost"
  Username: "admin"
  Password: "pYMuwWdrWULs8EUX"

JWTSeret:
  JWTEncodeKey: mysecret1234
